config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'mainpage#index'
  devise_for :users, path: 'accounts'
  resources :profiles, only: [:new, :create, :show, :edit, :update]
  resources :articles, path: 'blog' do
    resources :comments, only: [:create]
    collection do
      get :search, to: 'articles#search'
    end
  end
  get 'calculator', to: 'mainpage#calculator'
  get 'rules', to: 'mainpage#rules'
  get 'api', to: 'apis#index'
  get 'my-posts', to: 'articles#myposts'

end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, :description, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  layout 'blog'
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_user
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :check_current_user, only: [:edit, :update]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = @user.articles.build(article_params)
    if @article.save
      redirect_to my_posts_path, notice: "¡ Post creado exitosamente !"
    else
      render :action => 'new'
    end
  end

  def show
    @comments = @article.comments.paginate(page: params[:page], per_page: 5).order('created_at desc')
  end

  def myposts
    @articles = Article.where(user_id: @user).paginate(page: params[:page], per_page: 5).order('created_at desc')
  end

  def edit

  end

  def update
    if @article.update(article_params)
      redirect_to my_posts_path, notice: "¡ Se ha actualizado el Post satisfactoriamente !"
    else
      render :action => 'edit'
    end
  end

  def destroy
    if @article.destroy
      redirect_to my_posts_path, notice: "¡ Post Eliminado !"
    else
      redirect_to my_posts_path, alert: '¡ No fue posible eliminar el post seleccionado !'
    end
  end

  def search
    if params[:search].blank?
      redirect_to(articles_path, alert: "Debes Ingresar una palabra") and return
    else
      @parameter = params[:search].downcase
      @articles = Article.all.where('lower(title) LIKE :search', search: "%#{@parameter}%").paginate(page: params[:page], per_page: 5).order('created_at desc')
      @result = @articles.count
    end
  end

  private

  def set_user
    @user = current_user
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def check_current_user
    if current_user.present?
      if @article.user_id != @user.id
        redirect_back fallback_location: articles_path, alert: "Estas intentando acceder a un post que no has publicado"
        end
    else
      redirect_back fallback_location: articles_path, alert: "Tu Sesión ha expirado"
    end
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_comment_form.html.haml
.container
  = form_with(model: [@article,@article.comments.build], local:true) do |f|
    .form-group
      .row.justify-content-end
        .col-md-12.mt-2
          = f.label :body, 'Añadir Comentario', class: 'post-font form-post-font '
          = f.text_area :body, class: 'form-control shadow'
    .actions.text-right
      .form-group
        .row.justify-content-center
          .col-md-12
            = f.submit "Guardar", class: 'btn btn-outline-primary btn-sm'
            %button.btn.btn-sm.btn-outline-danger{"data-dismiss" => "modal", :type => "button"} Cancelar

app/views/articles/_form.html.haml
= form_with(model: @article, local:true) do |f|
  - if @article.errors.any?
    .row.justify-content-center
      .col-md-6
        #error_explanation.alert.alert-danger.alert-dismissible.fade.show
          %h4
            = pluralize(@article.errors.count, "error")
            al intentar registrar el Post:
          %ul
            - @article.errors.full_messages.each do |message|
              %li= message
          %button.close{ 'data-dismiss': 'alert' }
            %span x
  .form-group
    .row.justify-content-center
      .col-md-6
        = f.label :title, 'Título', class: 'form-title'
        = f.text_field :title, class: 'form-control', autofocus: true, autocomplete: "title"
  .form-group
    .row.justify-content-center
      .col-md-6
        = f.label :description, 'Contenido', class: 'form-title'
        = f.hidden_field :description, class: 'form-control', id: 'wys', required: 'true'
        %trix-editor.trix-editor{input:'wys'}
  .actions.text-right
    .form-group
      .row.justify-content-center
        .col-md-6
          = f.submit "Guardar", class: 'btn btn-outline-primary btn-sm'
          = link_to "Cancelar", my_posts_path, class: 'btn btn-outline-danger btn-sm'

app/views/articles/edit.html.haml
.container.mt-5
  %h2{class: 'text-center form-title'} Editar Post seleccionado
  = render 'form'

app/views/articles/index.html.haml
/ Page Content
.container
  .row
    / Blog Entries Column
    .col-md-8
      %h1.my-4.form-title.text-center#blog_title
        Supremacy Blog
        -# %small Secondary Text
      / Blog Post
      - @articles.each do |article|
        .card.mb-4.shadow
          -# %img.card-img-top{:alt => "Card image cap", :src => "http://placehold.it/750x300"}/
          %h3.card-title.card-header.form-title=article.title
          .card-body
            %p.card-text=simple_format("#{article.description.first(350)} ...") #"raw" tambien sirve
            %a.btn.btn-outline-primary.btn-sm{:href => article_path(article.id)} Seguir Leyendo →
          .card-footer.text-muted.text-right
            Posted on:
            =article.created_at.strftime('%d-%m-%Y')
            by
            %span{class:"font-weight-bold font-italic"}
              =article.user.name
      / Pagination
      .mt-3= will_paginate @articles
    / Sidebar Widgets Column
    .col-md-4
      / Search Widget
      .card.my-4
        %h5.card-header.form-title Buscador de Posts
        .card-body
          = form_tag(search_articles_path, method: 'get') do
            .input-group
              = search_field_tag :search, params[:search], placeholder: "Buscar por Título...", class: "form-control"
              -# %input.form-control{:placeholder => "Search for...", :type => "text"}/
              %span.input-group-btn
                = button_tag "Ir", :class => 'btn btn-outline-secondary',name: nil
                -# %button.btn.btn-secondary{:type => "button"} Go!
      / Categories Widget
      .card.my-4
        %h5.card-header.form-title Categories
        .card-body
          .row
            .col-lg-6
              %ul.list-unstyled.mb-0
                %li
                  %a{:href => "#"} Web Design
                %li
                  %a{:href => "#"} HTML
                %li
                  %a{:href => "#"} Freebies
            .col-lg-6
              %ul.list-unstyled.mb-0
                %li
                  %a{:href => "#"} JavaScript
                %li
                  %a{:href => "#"} CSS
                %li
                  %a{:href => "#"} Tutorials
      / Side Widget
      .card.my-4
        %h5.card-header.form-title Side Widget
        .card-body
          You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          %a(href="https://www.dropbox.com/sh/z6nphvps7ht1fik/AABD6JWA0MONAYiWGs1galLCa?dl=0") Fan Kit
  / /.row
/ /.container
/ Footer
-# %footer.py-5.bg-dark
-#   .container
-#     %p.m-0.text-center.text-white Copyright © David Villegas 2019
.footer-blog
  .container
    .row
      .col-sm-6
        %p Supremacy Clan
      .col-sm-6
        %p.pull-right
          Copyright © David Villegas 2019
          -# %a{:href => "http://designscrazed.org/"} David Villegas 2019

app/views/articles/myposts.html.haml
.container
  .row.justify-content-center
    .col-md-8
      %h2.my-4.form-title.text-center Mis Posts
      =link_to articles_path, class:'btn btn-outline-dark btn-sm' do
        Regresar
      - @articles.each do |article|
        .card.mt-2
          %h3{class:'card-header text-center form-title'}=article.title
          .card-body
            %p{class:'card-text'}=raw article.description
            .float-right
              =link_to edit_article_path(article.id), class:'btn btn-outline-primary btn-sm' do
                Editar
              %span
              =link_to article_path(article.id), method: 'delete', data: {confirm: '¿Esta seguro de eliminar el usuario seleccionado?'}, class:'btn btn-outline-danger btn-sm' do
                Eliminar
      .mt-3= will_paginate @articles

app/views/articles/new.html.haml
.container
  %h2{class: 'text-center my-4 form-title'} Crear Post
  = render 'form'

app/views/articles/search.html.haml
.container.pt-3
  .row.justify-content-center
    / Blog Entries Column
    .col-md-8
      / Blog Post
      -if !@articles.present?
        %h2.text-center.form-title.pt-3 No se encontraron resultados
        .container
          .row.justify-content-center
            .col.text-center
              = image_tag 'oops.jpg', height: '350px', width: '350px', class: 'img-fluid mb-3'
      -else
        %h2.text-center.form-title.pt-3= "Posts encontrados: #{@result}"
        - @articles.each do |article|
          .card.mb-4
            -# %img.card-img-top{:alt => "Card image cap", :src => "http://placehold.it/750x300"}/
            %h2.card-title.card-header=article.title
            .card-body
              %p.card-text=simple_format("#{article.description.first(350)} ...") #"raw" tambien sirve
              %a.btn.btn-outline-primary.btn-sm{:href => article_path(article.id)} Seguir Leyendo →
            .card-footer.text-muted.text-right
              Posted on:
              =article.created_at.strftime('%d-%m-%Y')
              by
              %span{class:"font-weight-bold font-italic"}
                =article.user.name
        / Pagination
        .mt-3= will_paginate @articles
  .row.justify-content-center
    =link_to articles_path, class:'btn btn-outline-dark mb-3 btn-sm' do
      Regresar

app/views/articles/show.html.haml
.container
  .row.justify-content-center
    .col-md-12
      %h2{class:'post-font post-font-title fix_top'}=@article.title
      %h3=raw @article.description
  .row.justify-content-end
    .col-md-5.signature
      %span{class:'text-center'}
        Escrito por:
        %span{class:"font-weight-bold font-italic"}
          - if @article.user.profile.present?
            =link_to "#{@article.user.name}", profile_path(@article.user.profile.id)
          -else
            =@article.user.name
        en fecha:
        %span{class:"font-weight-bold font-italic"}
          =@article.created_at.strftime('%d-%m-%Y')
  =link_to articles_path, class:'btn btn-sm btn-outline-dark mt-3' do
    Regresar
  .row.justify-content-start
    .col-12
      %hr
  .row.justify-content-center
    .col-md-8
      %h2{class:'pt-3 post-font post-font-comment'}Comentarios
      - if @comments.present?
        - @comments.each do |comment|
          .container.comment-box.mt-2.shadow
            .row
              - if comment.user.profile.present?
                .col-md-2.pt-2
                  = image_tag (url_for(comment.user.profile.avatar)), class: 'profile shadow'
              -else
                .col-md-2.pt-2
                  = image_tag ('default_avatar.png'), class: 'profile shadow'
              .col-md-10.mt-2
                %span{class: 'font-weight-bold'}=comment.user.name
                %h6{class:'comment-date font-italic'}=comment.created_at.strftime('%b %d, %Y at %H:%M')
                %p=comment.body
        -# .mt-3= will_paginate @comments
      - else
        %h5{class: 'font-italic'} No hay comentarios publicados
  .row.justify-content-center
    .col-md-8.mt-3.text-center
      - if @user.present?
        -# = render 'comment_form'
        %button.btn.btn-sm.btn-outline-dark{"data-target" => "#comment", "data-toggle" => "modal", :type => "button"}
          Comentar
  .mt-3= will_paginate @comments
  %br/
  #comment.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog{:role => "document"}
      .modal-content
        = render 'comment_form'